---
title: "Zooplankton QA Report"
output: html_document
params:
  clean_data: NULL
  raw_files: NULL
  compiled_csv: NULL
  missing_required: NULL
  negative_counts: NULL
  nonpositive_split_factor: NULL
  unexpected_sex_values: NULL
  duplicate_organism_rows: NULL
  station_standardization: NULL
  qa_link_issues: NULL
  qa_summary: NULL
  sample_summary: NULL
  sample_summary_csv: NULL
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(targets)
library(dplyr)
library(tibble)

clean_data <- params$clean_data
raw_files <- params$raw_files
compiled_csv <- params$compiled_csv
missing_required <- params$missing_required
negative_counts <- params$negative_counts
nonpositive_split_factor <- params$nonpositive_split_factor
unexpected_sex_values <- params$unexpected_sex_values
duplicate_organism_rows <- params$duplicate_organism_rows
station_standardization <- params$station_standardization
qa_link_issues <- params$qa_link_issues
qa_summary <- params$qa_summary
sample_summary <- params$sample_summary
sample_summary_csv <- params$sample_summary_csv
```

## Overview

```{r}
data.frame(
  n_rows = nrow(clean_data),
  n_samples = dplyr::n_distinct(clean_data$sample_num),
  n_source_files = dplyr::n_distinct(clean_data$source_file),
  n_taxa = dplyr::n_distinct(clean_data$species_name)
) |>
  knitr::kable()
```

## QA summary

```{r}
qa_summary |>
  knitr::kable()
```

## Sample summary

```{r}
sample_summary |>
  dplyr::arrange(source_file, sample_num) |>
  knitr::kable()
```

## Missing required values

```{r}
missing_required |>
  head(50) |>
  knitr::kable()
```

## Negative counts

```{r}
negative_counts |>
  head(50) |>
  knitr::kable()
```

## Nonpositive split factor

```{r}
nonpositive_split_factor |>
  head(50) |>
  knitr::kable()
```

## Unexpected sex values

```{r}
unexpected_sex_values |>
  head(50) |>
  knitr::kable()
```

## Duplicate organism rows

```{r}
duplicate_organism_rows |>
  head(50) |>
  knitr::kable()
```

## Station standardization

```{r}
station_standardization |>
  head(50) |>
  knitr::kable()
```

## QA link issues

```{r}
qa_link_issues |>
  head(50) |>
  knitr::kable()
```
